-- ============================================================
-- TFMS Software - Create All Tables (SQL Server Compatible)
-- Run this on: DESKTOP-01\SQLEXPRESS
-- ============================================================
USE TFMS_softwareDB;
GO

-- ── MASTERS ──────────────────────────────────────────────────

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Partners')
CREATE TABLE Partners (
    Id INT IDENTITY(1,1) PRIMARY KEY, Code NVARCHAR(MAX) NOT NULL UNIQUE,
    Name NVARCHAR(MAX) NOT NULL, Contact NVARCHAR(MAX) NOT NULL DEFAULT '',
    Mobile NVARCHAR(MAX) NOT NULL DEFAULT '', Email NVARCHAR(MAX) NOT NULL DEFAULT '',
    Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Owners')
CREATE TABLE Owners (
    Id INT IDENTITY(1,1) PRIMARY KEY, Code NVARCHAR(MAX) NOT NULL UNIQUE,
    Name NVARCHAR(MAX) NOT NULL, Contact NVARCHAR(MAX) NOT NULL DEFAULT '',
    Email NVARCHAR(MAX) NOT NULL DEFAULT '', Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Floors')
CREATE TABLE Floors (
    Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(MAX) NOT NULL,
    Number INT NOT NULL DEFAULT 0, Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='RoomStatuses')
CREATE TABLE RoomStatuses (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(MAX) NOT NULL UNIQUE);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='PaymentModes')
CREATE TABLE PaymentModes (
    Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(MAX) NOT NULL UNIQUE,
    Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active'
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='FundPools')
CREATE TABLE FundPools (
    Id INT IDENTITY(1,1) PRIMARY KEY, Code NVARCHAR(MAX) NOT NULL UNIQUE,
    Name NVARCHAR(MAX) NOT NULL, Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    Balance DECIMAL(18,2) NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='AccountsHeads')
CREATE TABLE AccountsHeads (
    Id INT IDENTITY(1,1) PRIMARY KEY, Code NVARCHAR(MAX) NOT NULL UNIQUE,
    Name NVARCHAR(MAX) NOT NULL, Type NVARCHAR(MAX) NOT NULL DEFAULT '',
    Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Designations')
CREATE TABLE Designations (
    Id INT IDENTITY(1,1) PRIMARY KEY, Code NVARCHAR(MAX) NOT NULL UNIQUE,
    Name NVARCHAR(MAX) NOT NULL, Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='OtherPersons')
CREATE TABLE OtherPersons (
    Id INT IDENTITY(1,1) PRIMARY KEY, Code NVARCHAR(MAX) NOT NULL UNIQUE,
    Designation NVARCHAR(MAX) NOT NULL DEFAULT '', Name NVARCHAR(MAX) NOT NULL,
    Mobile NVARCHAR(MAX) NOT NULL DEFAULT '', Email NVARCHAR(MAX) NOT NULL DEFAULT '',
    Address NVARCHAR(MAX) NOT NULL DEFAULT '', City NVARCHAR(MAX) NOT NULL DEFAULT '',
    State NVARCHAR(MAX) NOT NULL DEFAULT '', Pincode NVARCHAR(MAX) NOT NULL DEFAULT '',
    Remarks NVARCHAR(MAX) NOT NULL DEFAULT '', Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Roles')
CREATE TABLE Roles (
    Id INT IDENTITY(1,1) PRIMARY KEY, RoleCode NVARCHAR(MAX) NOT NULL UNIQUE,
    RoleName NVARCHAR(MAX) NOT NULL, Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO

-- ── CAMPS & ROOMS ─────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Camps')
CREATE TABLE Camps (
    Id INT IDENTITY(1,1) PRIMARY KEY, Code NVARCHAR(MAX) NOT NULL UNIQUE,
    Name NVARCHAR(MAX) NOT NULL, Rooms INT NOT NULL DEFAULT 0, Floors INT NOT NULL DEFAULT 0,
    Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='CampPartners')
CREATE TABLE CampPartners (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CampId INT NOT NULL REFERENCES Camps(Id) ON DELETE CASCADE,
    PartnerId INT NOT NULL REFERENCES Partners(Id),
    ShareType NVARCHAR(MAX) NOT NULL DEFAULT 'percentage', ShareValue DECIMAL(18,2) NOT NULL DEFAULT 0
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='CampOwners')
CREATE TABLE CampOwners (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CampId INT NOT NULL REFERENCES Camps(Id) ON DELETE CASCADE,
    OwnerId INT NOT NULL REFERENCES Owners(Id),
    ShareType NVARCHAR(MAX) NOT NULL DEFAULT 'percentage', ShareValue DECIMAL(18,2) NOT NULL DEFAULT 0
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Rooms')
CREATE TABLE Rooms (
    Id INT IDENTITY(1,1) PRIMARY KEY, RoomNo NVARCHAR(MAX) NOT NULL,
    CampId INT NOT NULL REFERENCES Camps(Id), FloorId INT NOT NULL REFERENCES Floors(Id),
    Occupied BIT NOT NULL DEFAULT 0, MonthlyPrice DECIMAL(18,2) NOT NULL DEFAULT 0,
    Status NVARCHAR(MAX) NOT NULL DEFAULT 'Vacant', OtherDetails NVARCHAR(MAX) NOT NULL DEFAULT '',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO

-- ── TENANTS & CONTRACTS ───────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Tenants')
CREATE TABLE Tenants (
    Id INT IDENTITY(1,1) PRIMARY KEY, Type NVARCHAR(MAX) NOT NULL DEFAULT 'Individual',
    Name NVARCHAR(MAX) NOT NULL, Passport NVARCHAR(MAX) NOT NULL DEFAULT '',
    Nationality NVARCHAR(MAX) NOT NULL DEFAULT '', EmiratesId NVARCHAR(MAX) NOT NULL DEFAULT '',
    Contact NVARCHAR(MAX) NOT NULL DEFAULT '', Whatsapp NVARCHAR(MAX) NOT NULL DEFAULT '',
    Email NVARCHAR(MAX) NOT NULL DEFAULT '', Address NVARCHAR(MAX) NOT NULL DEFAULT '',
    Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active', Company NVARCHAR(MAX) NOT NULL DEFAULT '',
    TradeLicense NVARCHAR(MAX) NOT NULL DEFAULT '', LicensingAuthority NVARCHAR(MAX) NOT NULL DEFAULT '',
    NumberOfCoOccupants NVARCHAR(MAX) NOT NULL DEFAULT '', PlotNo NVARCHAR(MAX) NOT NULL DEFAULT '',
    MakaniNo NVARCHAR(MAX) NOT NULL DEFAULT '', PropertyArea NVARCHAR(MAX) NOT NULL DEFAULT '',
    PremisesNo NVARCHAR(MAX) NOT NULL DEFAULT '', LessorName NVARCHAR(MAX) NOT NULL DEFAULT '',
    LessorEid NVARCHAR(MAX) NOT NULL DEFAULT '', LessorLicense NVARCHAR(MAX) NOT NULL DEFAULT '',
    LessorLicAuthority NVARCHAR(MAX) NOT NULL DEFAULT '', LessorEmail NVARCHAR(MAX) NOT NULL DEFAULT '',
    LessorPhone NVARCHAR(MAX) NOT NULL DEFAULT '',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Contracts')
CREATE TABLE Contracts (
    Id INT IDENTITY(1,1) PRIMARY KEY, ContractId NVARCHAR(MAX) NOT NULL UNIQUE,
    TenantId INT NOT NULL REFERENCES Tenants(Id), CampId INT NOT NULL REFERENCES Camps(Id),
    StartDate DATE NOT NULL, Months INT NOT NULL DEFAULT 12, EndDate DATE NOT NULL,
    MonthlyTotal DECIMAL(18,2) NOT NULL DEFAULT 0, ContractTotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='ContractRooms')
CREATE TABLE ContractRooms (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ContractId NVARCHAR(MAX) NOT NULL REFERENCES Contracts(ContractId) ON DELETE CASCADE,
    RoomId INT NOT NULL REFERENCES Rooms(Id)
);
GO

-- ── PAYMENTS & WAIVERS ────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Payments')
CREATE TABLE Payments (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ContractId NVARCHAR(MAX) NOT NULL REFERENCES Contracts(ContractId),
    InstallmentNo INT NOT NULL, Amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    DueDate DATE NOT NULL, PaidAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
    PaidDate DATE NULL, Status NVARCHAR(MAX) NOT NULL DEFAULT 'Pending',
    PaymentMode NVARCHAR(MAX) NOT NULL DEFAULT '', PaymentModeId INT NULL,
    ChequeNumber NVARCHAR(MAX) NOT NULL DEFAULT '', ClearanceDate NVARCHAR(MAX) NOT NULL DEFAULT '',
    Description NVARCHAR(MAX) NOT NULL DEFAULT '', ReceivedBy NVARCHAR(MAX) NOT NULL DEFAULT '',
    ReceivedContact NVARCHAR(MAX) NOT NULL DEFAULT '', FundPoolId INT NULL,
    FundPoolName NVARCHAR(MAX) NOT NULL DEFAULT '', IssuedBy NVARCHAR(MAX) NOT NULL DEFAULT ''
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='Waivers')
CREATE TABLE Waivers (
    Id INT IDENTITY(1,1) PRIMARY KEY, TenantId INT NOT NULL REFERENCES Tenants(Id),
    ContractId NVARCHAR(MAX) NOT NULL REFERENCES Contracts(ContractId),
    InstallmentNo INT NOT NULL, OriginalAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
    WaiverAmount DECIMAL(18,2) NOT NULL DEFAULT 0, BalanceAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
    Remark NVARCHAR(MAX) NOT NULL DEFAULT '', WaiverDate DATE NOT NULL
);
GO

-- ── USERS ────────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='AppUsers')
CREATE TABLE AppUsers (
    Id INT IDENTITY(1,1) PRIMARY KEY, UserId NVARCHAR(MAX) NOT NULL UNIQUE,
    Name NVARCHAR(MAX) NOT NULL, Username NVARCHAR(MAX) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(MAX) NOT NULL, Role NVARCHAR(MAX) NOT NULL DEFAULT '',
    Source NVARCHAR(MAX) NOT NULL DEFAULT '', SourceId INT NULL,
    Contact NVARCHAR(MAX) NOT NULL DEFAULT '', Email NVARCHAR(MAX) NOT NULL DEFAULT '',
    LoginAccess NVARCHAR(MAX) NOT NULL DEFAULT 'enabled', Status NVARCHAR(MAX) NOT NULL DEFAULT 'Active',
    LastLogin DATETIME2 NULL, MenuAccess NVARCHAR(MAX) NOT NULL DEFAULT '{}',
    IsAdmin BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(), UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO

-- ── SEED DATA ────────────────────────────────────────────────
IF NOT EXISTS (SELECT 1 FROM AppUsers WHERE Username='admin')
INSERT INTO AppUsers (UserId,Name,Username,PasswordHash,Role,IsAdmin,Status,LoginAccess,MenuAccess,CreatedAt,UpdatedAt)
VALUES('USR-000001','System Administrator','admin',
    '$2a$11$K8F4wVpIkq6U2xN3mZP1YeO8dEqRpLvCvMjHj9nTuSGmWzXpDkEwy',
    'Admin',1,'Active','enabled','{}',GETUTCDATE(),GETUTCDATE());
GO

IF NOT EXISTS (SELECT 1 FROM PaymentModes WHERE Name='Cash')
INSERT INTO PaymentModes(Name,Status) VALUES('Cash','Active'),('Cheque','Active'),
    ('Bank Transfer','Active'),('Online Payment','Active'),('Credit Card','Active'),('Debit Card','Active');
GO

IF NOT EXISTS (SELECT 1 FROM RoomStatuses WHERE Name='Vacant')
INSERT INTO RoomStatuses(Name) VALUES('Vacant'),('Occupied'),('Maintenance'),('Reserved');
GO

PRINT 'All tables and seed data created successfully!';
GO
