-- ============================================================
-- TFMS: Stored Procedure to clean all data
-- Keeps: AppUsers, Floors, RoomStatuses, PaymentModes, Roles
-- Usage: EXEC sp_CleanAllData
-- ============================================================
USE TFMS_TestSoftwareDB;
GO

CREATE OR ALTER PROCEDURE sp_CleanAllData
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. Disable FK constraints on all target tables
    ALTER TABLE Waivers NOCHECK CONSTRAINT ALL;
    ALTER TABLE TxnRecords NOCHECK CONSTRAINT ALL;
    ALTER TABLE Payments NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractRoomInstallments NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractRoomsTrns NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractInstallments NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractRooms NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractCamps NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractTerms NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractCancellations NOCHECK CONSTRAINT ALL;
    ALTER TABLE ContractRenewals NOCHECK CONSTRAINT ALL;
    ALTER TABLE Contracts NOCHECK CONSTRAINT ALL;
    ALTER TABLE OwnerTransactions NOCHECK CONSTRAINT ALL;
    ALTER TABLE OwnerInstallments NOCHECK CONSTRAINT ALL;
    ALTER TABLE OwnerContracts NOCHECK CONSTRAINT ALL;
    ALTER TABLE OutgoingPayments NOCHECK CONSTRAINT ALL;
    ALTER TABLE Incomes NOCHECK CONSTRAINT ALL;
    ALTER TABLE Expenses NOCHECK CONSTRAINT ALL;
    ALTER TABLE Rooms NOCHECK CONSTRAINT ALL;
    ALTER TABLE CampPartners NOCHECK CONSTRAINT ALL;
    ALTER TABLE CampOwners NOCHECK CONSTRAINT ALL;
    ALTER TABLE Camps NOCHECK CONSTRAINT ALL;
    ALTER TABLE Tenants NOCHECK CONSTRAINT ALL;
    ALTER TABLE Partners NOCHECK CONSTRAINT ALL;
    ALTER TABLE Owners NOCHECK CONSTRAINT ALL;
    ALTER TABLE FundPools NOCHECK CONSTRAINT ALL;
    ALTER TABLE AccountsHeads NOCHECK CONSTRAINT ALL;
    ALTER TABLE Designations NOCHECK CONSTRAINT ALL;
    ALTER TABLE OtherPersons NOCHECK CONSTRAINT ALL;
    ALTER TABLE CompanyAssets NOCHECK CONSTRAINT ALL;
    ALTER TABLE Staff NOCHECK CONSTRAINT ALL;
    ALTER TABLE ActivityLogs NOCHECK CONSTRAINT ALL;

    -- 2. Delete all data (children first)
    DELETE FROM Waivers;
    DELETE FROM TxnRecords;
    DELETE FROM Payments;
    DELETE FROM ContractRoomInstallments;
    DELETE FROM ContractRoomsTrns;
    DELETE FROM ContractInstallments;
    DELETE FROM ContractRooms;
    DELETE FROM ContractCamps;
    DELETE FROM ContractTerms;
    DELETE FROM ContractCancellations;
    DELETE FROM ContractRenewals;
    DELETE FROM Contracts;
    DELETE FROM OwnerTransactions;
    DELETE FROM OwnerInstallments;
    DELETE FROM OwnerContracts;
    DELETE FROM OutgoingPayments;
    DELETE FROM Incomes;
    DELETE FROM Expenses;
    DELETE FROM Rooms;
    DELETE FROM CampPartners;
    DELETE FROM CampOwners;
    DELETE FROM Camps;
    DELETE FROM Tenants;
    DELETE FROM Partners;
    DELETE FROM Owners;
    DELETE FROM FundPools;
    DELETE FROM AccountsHeads;
    DELETE FROM Designations;
    DELETE FROM OtherPersons;
    DELETE FROM CompanyAssets;
    DELETE FROM Staff;
    DELETE FROM ActivityLogs;

    -- 3. Reseed identity columns to 0
    DBCC CHECKIDENT ('Waivers', RESEED, 0);
    DBCC CHECKIDENT ('TxnRecords', RESEED, 0);
    DBCC CHECKIDENT ('Payments', RESEED, 0);
    DBCC CHECKIDENT ('ContractRoomInstallments', RESEED, 0);
    DBCC CHECKIDENT ('ContractRoomsTrns', RESEED, 0);
    DBCC CHECKIDENT ('ContractInstallments', RESEED, 0);
    DBCC CHECKIDENT ('ContractRooms', RESEED, 0);
    DBCC CHECKIDENT ('ContractCamps', RESEED, 0);
    DBCC CHECKIDENT ('ContractTerms', RESEED, 0);
    DBCC CHECKIDENT ('ContractCancellations', RESEED, 0);
    DBCC CHECKIDENT ('ContractRenewals', RESEED, 0);
    DBCC CHECKIDENT ('Contracts', RESEED, 0);
    DBCC CHECKIDENT ('OwnerTransactions', RESEED, 0);
    DBCC CHECKIDENT ('OwnerInstallments', RESEED, 0);
    DBCC CHECKIDENT ('OwnerContracts', RESEED, 0);
    DBCC CHECKIDENT ('OutgoingPayments', RESEED, 0);
    DBCC CHECKIDENT ('Incomes', RESEED, 0);
    DBCC CHECKIDENT ('Expenses', RESEED, 0);
    DBCC CHECKIDENT ('Rooms', RESEED, 0);
    DBCC CHECKIDENT ('CampPartners', RESEED, 0);
    DBCC CHECKIDENT ('CampOwners', RESEED, 0);
    DBCC CHECKIDENT ('Camps', RESEED, 0);
    DBCC CHECKIDENT ('Tenants', RESEED, 0);
    DBCC CHECKIDENT ('Partners', RESEED, 0);
    DBCC CHECKIDENT ('Owners', RESEED, 0);
    DBCC CHECKIDENT ('FundPools', RESEED, 0);
    DBCC CHECKIDENT ('AccountsHeads', RESEED, 0);
    DBCC CHECKIDENT ('Designations', RESEED, 0);
    DBCC CHECKIDENT ('OtherPersons', RESEED, 0);
    DBCC CHECKIDENT ('CompanyAssets', RESEED, 0);
    DBCC CHECKIDENT ('Staff', RESEED, 0);
    DBCC CHECKIDENT ('ActivityLogs', RESEED, 0);

    -- 4. Re-enable FK constraints
    ALTER TABLE Waivers WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE TxnRecords WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Payments WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractRoomInstallments WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractRoomsTrns WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractInstallments WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractRooms WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractCamps WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractTerms WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractCancellations WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ContractRenewals WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Contracts WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE OwnerTransactions WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE OwnerInstallments WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE OwnerContracts WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE OutgoingPayments WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Incomes WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Expenses WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Rooms WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE CampPartners WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE CampOwners WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Camps WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Tenants WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Partners WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Owners WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE FundPools WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE AccountsHeads WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Designations WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE OtherPersons WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE CompanyAssets WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE Staff WITH CHECK CHECK CONSTRAINT ALL;
    ALTER TABLE ActivityLogs WITH CHECK CHECK CONSTRAINT ALL;
END
GO
